/**
 * Strips supplier-identity leaks out of customer-facing product descriptions.
 *
 * Found while working the ledger's backlog: 44 products (mostly Hill
 * Interiors imports, a few Ancient Wisdom ones) carry description blocks
 * that name the actual dropship supplier, or worse — several carry a live
 * hyperlink straight back to the supplier's own retail page on
 * hill-interiors.com, one of them tagged `?utm_source=chatgpt.com`. That tag
 * is the tell: this content was generated by browsing the supplier's own
 * product page rather than written independently, which is exactly what
 * "No supplier data feed. Every product is written individually, not
 * copied from the supplier's description" (the standing constraint) exists
 * to prevent. The live link is the more urgent half of the bug — it sends a
 * Kaiku customer straight to the supplier who could sell them the same item
 * directly, cutting Kaiku out entirely.
 *
 * What this script removes, block by block:
 *   - Any span whose markDef is a link to hill-interiors.com — the span and
 *     its markDef both go. If that was the block's only real content (the
 *     lone "(hill-interiors.com)" citation blocks), the whole block goes;
 *     otherwise the surrounding sentence is kept and just tidied.
 *   - Whole blocks whose only content is "Brand: Hill Interiors",
 *     "Brand: Ancient Wisdom", or "Supplier Code: <n>" — a spec line naming
 *     the dropship supplier has no reason to be customer-facing.
 *   - The "Supplied by Ancient Wisdom" bullet, wherever it's its own bullet.
 *
 * What this script deliberately does NOT touch: prose content otherwise.
 * Several of these descriptions may still be substantively similar to the
 * supplier's own copy — that's a separate, harder question (duplicate-
 * content risk) this script isn't equipped to judge, and it's flagged in
 * the ledger for Damien rather than guessed at here.
 *
 *   pnpm tsx --env-file=.env.local scripts/fix-supplier-leaks-in-descriptions.ts
 *   pnpm tsx --env-file=.env.local scripts/fix-supplier-leaks-in-descriptions.ts --apply
 */
import { mkdirSync, writeFileSync } from "node:fs";

import { createClient } from "@sanity/client";

const apply = process.argv.includes("--apply");
const token = process.env.SANITY_API_WRITE_TOKEN;
if (apply && !token) {
  console.error("SANITY_API_WRITE_TOKEN is not set — refusing to --apply.");
  process.exit(1);
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "huh1e45n",
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "production",
  apiVersion: "2025-01-01",
  token,
  useCdn: false,
  perspective: "raw",
});

interface Span {
  _key: string;
  _type: "span";
  text: string;
  marks: string[];
}
interface MarkDef {
  _key: string;
  _type: string;
  href?: string;
}
interface Block {
  _key: string;
  _type: string;
  children?: Span[];
  markDefs?: MarkDef[];
  style?: string;
  listItem?: string;
  level?: number;
}

const SUPPLIER_LINK_HOST = "hill-interiors.com";

function isSupplierLinkMarkKey(markDefs: MarkDef[], key: string): boolean {
  const def = markDefs.find((m) => m._key === key);
  return !!def?.href?.includes(SUPPLIER_LINK_HOST);
}

/** True for a whole block whose only job is naming the supplier directly. */
function isWholeBlockLeak(text: string): boolean {
  const t = text.trim();
  return (
    /^Brand:\s*Hill Interiors$/i.test(t) ||
    /^Brand:\s*Ancient Wisdom$/i.test(t) ||
    /^Supplier Code:\s*\S+$/i.test(t) ||
    /^Supplied by Ancient Wisdom$/i.test(t)
  );
}

/**
 * Removes any span linking to the supplier's own site from a block, and
 * tidies the punctuation/whitespace that removal leaves behind. Returns
 * null if nothing meaningful is left, in which case the caller drops the
 * whole block.
 */
function stripSupplierLinks(block: Block): Block | null {
  const children = block.children ?? [];
  const markDefs = block.markDefs ?? [];
  const removed = children.map((s) =>
    s.marks.some((m) => isSupplierLinkMarkKey(markDefs, m)),
  );

  // A bare "(" or ")" left dangling next to a removed link span — on either
  // side, since the opening bracket is *before* the link that gets cut —
  // is orphaned punctuation, not real content, and goes too.
  const isOrphanPunctuation = (span: Span, index: number): boolean => {
    if (!/^[()\s]*$/.test(span.text) || span.text.trim().length > 1)
      return false;
    const prevRemoved = index > 0 && removed[index - 1];
    const nextRemoved = index < children.length - 1 && removed[index + 1];
    return !!(prevRemoved || nextRemoved);
  };

  const cleaned: Span[] = children.filter(
    (span, i) => !removed[i] && !isOrphanPunctuation(span, i),
  );

  const usedMarkKeys = new Set(cleaned.flatMap((s) => s.marks));
  const newMarkDefs = markDefs.filter((m) => usedMarkKeys.has(m._key));

  const joined = cleaned
    .map((s) => s.text)
    .join("")
    .trim();
  // Nothing left, or nothing left but stray punctuation — the whole block
  // existed only to carry the supplier link.
  if (!joined || /^[()\s]*$/.test(joined)) return null;

  // Trim stray trailing/leading whitespace left on the outer spans.
  cleaned[0] = { ...cleaned[0]!, text: cleaned[0]!.text.replace(/^\s+/, "") };
  cleaned[cleaned.length - 1] = {
    ...cleaned[cleaned.length - 1]!,
    text: cleaned[cleaned.length - 1]!.text.replace(/\s+$/, ""),
  };

  return { ...block, children: cleaned, markDefs: newMarkDefs };
}

function blockHasSupplierLink(block: Block): boolean {
  const markDefs = block.markDefs ?? [];
  return (block.children ?? []).some((s) =>
    s.marks.some((m) => isSupplierLinkMarkKey(markDefs, m)),
  );
}

function flattenText(block: Block): string {
  return (block.children ?? []).map((s) => s.text).join("");
}

interface ProductResult {
  id: string;
  title: string;
  blocksBefore: number;
  blocksAfter: number;
  blocksRemoved: number;
  blocksEdited: number;
}

async function main() {
  const rows: {
    _id: string;
    title: string;
    description: Block[];
  }[] = await client.fetch(`*[_type=="product"]{_id, title, description}`);

  const results: ProductResult[] = [];

  for (const row of rows) {
    const blocks = row.description ?? [];
    const affected = blocks.some(
      (b) => blockHasSupplierLink(b) || isWholeBlockLeak(flattenText(b)),
    );
    if (!affected) continue;

    const newBlocks: Block[] = [];
    let removed = 0;
    let edited = 0;
    for (const block of blocks) {
      const text = flattenText(block);
      if (isWholeBlockLeak(text)) {
        removed += 1;
        continue;
      }
      if (blockHasSupplierLink(block)) {
        const fixed = stripSupplierLinks(block);
        if (fixed === null) {
          removed += 1;
          continue;
        }
        edited += 1;
        newBlocks.push(fixed);
        continue;
      }
      newBlocks.push(block);
    }

    results.push({
      id: row._id,
      title: (row.title ?? "").replace(" | Kaiku", ""),
      blocksBefore: blocks.length,
      blocksAfter: newBlocks.length,
      blocksRemoved: removed,
      blocksEdited: edited,
    });

    console.log(
      `${row._id}\t${(row.title ?? "").replace(" | Kaiku", "")}\t-${removed} blocks, ~${edited} edited`,
    );

    if (!apply) continue;
    await client.patch(row._id).set({ description: newBlocks }).commit();
  }

  console.log(
    `\n${apply ? "Fixed" : "Would fix"} ${results.length} products (${results.reduce((n, r) => n + r.blocksRemoved, 0)} blocks removed, ${results.reduce((n, r) => n + r.blocksEdited, 0)} blocks edited).`,
  );

  mkdirSync("docs/change-log", { recursive: true });
  writeFileSync(
    "docs/change-log/2026-09-04-fix-supplier-leaks-in-descriptions.json",
    `${JSON.stringify({ apply, results }, null, 2)}\n`,
  );

  if (!apply) console.log("\nDry run — re-run with --apply.");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
